apiVersion: autoscaler.mongodb.io/v1alpha1
kind: MongodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: mongodboperator
    app.kubernetes.io/managed-by: kustomize
  name: mongodautoscaler-sample
spec:
  # TODO(user): Add fields here
